name: run npm-version pipeline
on:  
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      #upload a new version to npm
      - name: 'Get Tag Name'
        id: tagname
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/tags/}

      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm install
      
      - name: Publish package on NPM 📦
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}