name: run npm-version pipeline
on:  
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      #upload a new version to npm
      - name: 'Get Tag Name'
        id: tagname
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
      
      - name: 'Upload to NPM'
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: ${{ steps.tagname.outputs.tag }}